spring:
  application:
    name: ReactiveStreamsDemo
  data:
    mongodb:
      uri: mongodb+srv://springstudent:springstudent@first-cluster.vuamnew.mongodb.net/?retryWrites=true&w=majority
      database: employee-db

